name = "ComplexPortraits"
uuid = "17699382-6153-4e65-8b03-b2dc23b1a9dc"
authors = ["Christian Ludwig <ludwig@ma.tum.de>"]
version = "0.1.1"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
